name: flutter_miniplayer
description: A lightweight flutter package to simplify the creation of a miniplayer.
version: 1.0.1
homepage: https://www.michelmelo.pt
repository: https://github.com/michelmelo/flutter-miniplayer

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.0.0"
dependencies:
  flutter:
    sdk: flutter
